#!/bin/bash

CF_S="/usr/local/bin/cf-sketch --expert --installsource https://raw.github.com/ahdinosaur/design-center/master/sketches/cfsketches"


DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

$CF_S --generate

